#!/usr/bin/env bash

# 	symlink all of the rc files
##	going to hardcode the dotfile for safety instead of 
##	looping over everything in directory
DF_DIR="$(pwd)/"

files=(
  .Xauthority
	.Xresources
	.bashrc
	.vimrc
	.Xdefaults
	.bash_profile
	.pinerc
  .config/nvim/init.vim
  .bash_k8s_extension
  .inputrc
)

all_dirs='~/dev
    ~/.config/nvim'

for d in $all_dirs; do
    if [[ ! -e $d ]]; then
        printf "Going to create directory tree $d"
        mkdir -p $d
    fi
done

if [[ ! -e ~/.local/share/nvim/site/autoload/plug.vim ]]; then
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

cd "$DF_DIR"
for file in ${files[@]}; do
	# sanity check
	if [[ ! -e "$file" ]]; then
		printf "$file does not exist!\n"
		continue
	fi
	# symlink? then update
	if [[ -h "$HOME/$file" ]]; then
		printf "$HOME/$file symlink already exists, updating\n"
		rm "$HOME/$file"
	fi
	# already in home dir?
	if [[ -e "$HOME/$file" ]]; then
		printf "$HOME/$file file exists, replace (y/n)\n"
		isValid=false
		while [ $isValid = false ]; do
			read RESPONSE
			case $RESPONSE in
				y)
					isValid=true
					rm "$HOME/$file"
					;;
				n)
					isValid=true
					continue
					;;
				*)
					printf "%s is not a valid response\n" $RESPONSE
					continue
					;;
			esac
		done
		if [[ "n" == "$RESPONSE" ]]; then
			continue
		fi
	fi
    mkdir -p $(dirname "$HOME/$file")
	ln -s "$DF_DIR$file" "$HOME/$file"
done
